### ISSUE TITLE
2주차 스터디 인증하기!

### ISSUE THREAD

**Issue by kaiwind7** [daybreak6/do-it-vuejs#2]

**Comment by kaiwind7** [comment]
```html
<html>
    <head>
        <title>Vue Componenct Registration</title>
    </head>
    <body>
        <div id="app">
            <button>컴포넌트 등록</button>
            <my-componenct></my-componenct>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/vue@2.5.2/dist/vue.js"></script>
        <script>
            Vue.component('my-componenct', {
                template: '<div>전역 컴포넌트가 등록되었습니다!</div>'
            });

            new Vue({
                el: '#app'
            })
        </script>
    </body>
</html>
```
![image](https://user-images.githubusercontent.com/51537469/113503602-e6239e80-956d-11eb-8af8-31d45fbe057a.png)

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Vue Componencts Registration Quiz</title>
    </head>
    <body>
        <div id="app">
            <header>
                <h3>{{ message }}</h3>
            </header>
            <todo-footer></todo-footer>
            <todo-list></todo-list>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/vue@2.5.2/dist/vue.js"></script>
        <script src="js/vendor/vue.js"></script>
        <script src="js/app.js"></script>               
    </body>
</html>
```
```js
var cmp = {
	template: '<p>This is another local child component</p>'
};

Vue.component('tood-footer', {
    template: '<P>This is another global child component</P>'
})

var app = new Vue({
    el: '#app',
    data: {
        message: 'This is a parent component'
    },

    // 실습 #2 - 'todo-list' 컴포넌트 지역등록
    components: {
        'todo-list': cmp
    }
})
```
![image](https://user-images.githubusercontent.com/51537469/113604237-f0ce5880-967f-11eb-8aa4-4c294fcbb309.png)

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <title>Document</title>
</head>
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.2/dist/vue.js"></script>
<body>
    <div id="app">
        <child-component></child-component>
    </div>    
</body>
<script>
    var eventBus = new Vue();
    Vue.component('child-component', {
        template: '<div>하위 컴포넌트 영역입니다.<button v-on:click="showLog">show</button></div>',
        methods: {
            showLog: function() {
                eventBus.$emit('triggerEventBus', 100);
            }
        }
    });

    var app = new Vue({
        el: '#app',
        created: function() {
            eventBus.$on('triggerEventBus', function(value) {
                console.log('이벤트를 전달받음, 전달받은 값 : ', value);
            })
        }
    })
</script>
</html>
```
![image](https://user-images.githubusercontent.com/51537469/114309789-6aa08f00-9b23-11eb-9e10-d9c2dd958ad8.png)

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vue Components Communication Quiz</title>
  </head>
  <body>
    <div id="app">
      <child-component v-bind:propsdata="message"></child-component>
      <sibling-component v-bind:propsdata="anotherMessage"></sibling-component>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.2/dist/vue.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>
```

```javascript
Vue.component('sibling-component', {
    props: ['propsdata'],
    template: '<p>{{propsdata}}</p>'
});


Vue.component('child-component', {
    props: ['propsdata'],
    template: '<p>{{propsdata}}</p>'
});

var app = new Vue({
    el: '#app',
    data: {
        message: 'Hello Vue! passed from Parent Componenct',
        anotherMessage: 'Hello Vue! passed from Parent Componenct2'
    }
})
```
![image](https://user-images.githubusercontent.com/51537469/114309928-ec90b800-9b23-11eb-803c-522e8c756485.png)

**Comment by leekk12345** [comment]
3-03
![3-03](https://user-images.githubusercontent.com/26925737/113576414-7e974d00-965a-11eb-8f89-058291757bc3.JPG)
03-4
![03-4](https://user-images.githubusercontent.com/26925737/113576431-822ad400-965a-11eb-8f4a-3df8a71f2c07.JPG)
03-5
![03-5](https://user-images.githubusercontent.com/26925737/113576436-83f49780-965a-11eb-9f12-fe1b6c20efc5.JPG)
03-6
![03-6](https://user-images.githubusercontent.com/26925737/113576442-8525c480-965a-11eb-9809-a7118ed7ae77.JPG)
03-7
![03-7](https://user-images.githubusercontent.com/26925737/113576444-85be5b00-965a-11eb-8553-1b9a64c72fb2.JPG)
03-8
![03-8](https://user-images.githubusercontent.com/26925737/113576447-86ef8800-965a-11eb-83c0-0c6068871309.JPG)
03-9
![03-9](https://user-images.githubusercontent.com/26925737/113576449-8820b500-965a-11eb-9748-7a851984007c.JPG)
03-10
![03-10](https://user-images.githubusercontent.com/26925737/113576452-8951e200-965a-11eb-8ac7-191a8da214d0.JPG)

quiz03-2
![quiz1](https://user-images.githubusercontent.com/26925737/113576474-9242b380-965a-11eb-90b6-44b62a9defd9.JPG)
![quiz1-1](https://user-images.githubusercontent.com/26925737/113576595-cd44e700-965a-11eb-9b63-30ea5862da1d.JPG)

quiz03-3
![quiz2](https://user-images.githubusercontent.com/26925737/113576605-cfa74100-965a-11eb-9671-088770beecfb.JPG)
![quiz2-2](https://user-images.githubusercontent.com/26925737/113576611-d1710480-965a-11eb-8ffc-8d05a5505c36.JPG)

**Comment by LangVE** [comment]
![image](https://user-images.githubusercontent.com/24932090/113607505-3c830100-9684-11eb-886a-8f63cc70b0d4.png)

https://github.com/LangVE/do-it-vuejs

**Comment by rockee1230** [comment]
![3 2 1 예제-전역_컴포넌트_등록](https://user-images.githubusercontent.com/76459457/113811173-b0b5c580-97a6-11eb-95de-9bf15b7611c2.png)
![3 2 2 예제-지역_컴포넌트_등록](https://user-images.githubusercontent.com/76459457/113811191-b90e0080-97a6-11eb-8baf-eda3ad1dc477.png)
![3 2 3 예제-전역_지역_컴포넌트_등록](https://user-images.githubusercontent.com/76459457/113811213-c0350e80-97a6-11eb-881f-5e95183e59d3.png)
![3 2 4 예제-두번째_인스턴스](https://user-images.githubusercontent.com/76459457/113811229-c62aef80-97a6-11eb-8683-38953bebc10f.png)
![3 2 5 실습-전역_지역_컴포넌트](https://user-images.githubusercontent.com/76459457/113811243-cb883a00-97a6-11eb-89c5-50a257c4de37.png)
![3 3 1 예제-컴포넌트_데이터참조_불가](https://user-images.githubusercontent.com/76459457/113811253-d0e58480-97a6-11eb-8b8c-5faed44cafa8.png)
![3 3 2 예제-상위_하위_props데이터전달](https://user-images.githubusercontent.com/76459457/113811264-d5aa3880-97a6-11eb-85c7-d50989279c09.png)
![3 3 3 예제-이벤트전달](https://user-images.githubusercontent.com/76459457/113811278-dba01980-97a6-11eb-9ad7-8fbc11dba212.png)
![3 3 4 예제-이벤트버스](https://user-images.githubusercontent.com/76459457/113811285-e064cd80-97a6-11eb-9d4f-d83086414aa8.png)
![3 3 5 실습-props데이터_대입](https://user-images.githubusercontent.com/76459457/113811293-e5298180-97a6-11eb-95cd-40b3eb90d51a.png)
