### ISSUE TITLE
5주차 스터디 인증하기!

### ISSUE THREAD

**Issue by kaiwind7** [daybreak6/do-it-vuejs#5]

**Comment by kaiwind7** [comment]
![image](https://user-images.githubusercontent.com/51537469/116381797-31209100-a850-11eb-9a08-506edf92afa5.png)

**Comment by LangVE** [comment]
https://github.com/LangVE/do-it-vuejs
![image](https://user-images.githubusercontent.com/24932090/116917438-a09be380-ac89-11eb-920e-335561d88238.png)
